# Generated by Django 6.0.7 on 2026-07-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
    ]
